name: sqliteviewer
description: A new Flutter project.

publish_to: "none"

version: 0.2.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  code_text_field: ^1.1.0
  cupertino_icons: ^1.0.2
  desktop_drop: ^0.4.4
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_storage: ^2.1.1
  meta: ^1.9.1
  overlay_support: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  syncfusion_flutter_datagrid: ^26.2.9

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
