name: sqliteviewer
description: A new Flutter project.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.0
  file_picker: ^5.3.3
  syncfusion_flutter_datagrid: ^22.2.9
  get_storage: ^2.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  equatable: ^2.0.5
  sqflite_common_ffi: ^2.3.0+2
  overlay_support: ^2.1.0
  desktop_drop: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
